apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "example.fullname" . }}
  labels:
    {{- if .Values.ticket }}
    deployticket: {{ .Values.ticket }}
    {{- end }}
        {{- if .Values.action }}
    action: {{ .Values.action }}
    {{- end }}
    {{- include "example.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.notifications }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "example.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "example.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: workload
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
