{{- range $deploymentName, $deployment := .Values.deployments }}
{{- $namespace := print "-" $.Release.Namespace }}
{{- $chartName := print $.Chart.Name "-" }}
{{- if (and (gt $deployment.replicas 0.0) (or (eq $deploymentName (trimSuffix $namespace (trimPrefix $chartName $.Release.Name))) $.Values.multiDeploymentEnabled)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "slydell.fullname" $ }}
  labels: {{ include "slydell.labels" $ | nindent 4 }}
    deployment: {{ $deploymentName }}
data:
  {{ toYaml $.Values.commonEnvs | nindent 2 }}
  {{ toYaml $deployment.extraEnvs | nindent 2 }}
---
{{ end }}
{{ end }}
