{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "slydell.fullname" . }}
spec:
  dataFrom:
  {{-  tpl (toYaml .Values.externalSecrets.dataFrom) . | nindent 2 }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.kind }}
    name: {{ .Values.externalSecrets.secretStore }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: slydell-general-new
{{- end }}
