{{- range $deploymentName, $deployment := .Values.deployments }}
{{- $namespace := print "-" $.Release.Namespace }}
{{- $chartName := print $.Chart.Name "-" }}
{{- if (and (gt $deployment.replicas 0.0) (or (eq $deploymentName (trimSuffix $namespace (trimPrefix $chartName $.Release.Name))) $.Values.multiDeploymentEnabled)) -}}
{{- if $deployment.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels: {{ include "slydell.labels" $ | nindent 4 }}
    deployment: {{ $deploymentName }}
  name: {{ template "slydell.fullname" $ }}
  annotations:
    {{- range $key, $value := $deployment.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if and $deployment.ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $deployment.ingress.className }}
  {{- end }}
  rules:
    - host: {{ $deployment.ingress.host.url }}
      http:
        paths:
          - path: {{ $deployment.ingress.host.path }}
            backend:
              service:
                name: {{ template "slydell.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: ImplementationSpecific
  {{- if $deployment.ingress.tls }}
  tls:
{{ toYaml $deployment.ingress.tls | indent 4 }}
  {{- end }}
---
{{ end }}
{{ end }}
{{ end }}
