{{- if eq .Values.secretEnabled "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "slydell.fullname" . }}
  labels: {{ include "slydell.labels" . | nindent 4 }}
data:
  SLYDELL_MONGO_USERNAME: "mongo_username"
  SLYDELL_MONGO_PASSWORD: "mongo_password"
  SLYDELL_JWT_SECRET: "signing_secret"
  SLYDELL_EMAIL_SENDGRID_API_KEY: "sendgrid_api_key"
  SLYDELL_AWS_ACCESS_KEY_ID: "aws_key"
  SLYDELL_AWS_SECRET_ACCESS_KEY: "aws_secret"
  SLYDELL_STORE_MATTERS_TOKEN: "42matters_api_key"
  SLYDELL_STORE_APPFIGURES_CLIENT_KEY: "appfigures_client_key"
  SLYDELL_STORE_APPFIGURES_TOKEN: "appfigures_auth_token"
  SLYDELL_SALESFORCE_CLIENT_ID: "salesforce_client_id"
  SLYDELL_SALESFORCE_CLIENT_SECRET: "salesforce_client_secret"
  SLYDELL_SALESFORCE_USERNAME: "salesforce_username"
  SLYDELL_SALESFORCE_PASSWORD: "salesforce_password"
  SLYDELL_TIPALTI_KEY: "tipalti_encrypt_key"
{{- end }}