apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::320005014399:role/{{ .Values.roleName }}
  labels: {{ include "slydell.labels" $ | nindent 4 }}
