apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: example-
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - run.sh=start.sh
  name: start
- files:
  - run.sh=rollback.sh
  name: rollback
- files: 
  - run.sh=step.sh
  name: step

resources:
  - secrets.yaml
