apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: deployments
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: deployments/pe
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend-cicd
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
