name: Build and Publish Images
on:
  workflow_dispatch: 
permissions:
  id-token: write
  contents: write
  # https://stackoverflow.com/questions/72248956/github-action-with-docker-makes-error-exporting-to-image-403-forbidden-error
  packages: write
  pull-requests: read
env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  build-and-publish:
    name: Build and Publish Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v4
        with:
          repository: 'Vungle/slydell'
          token: ${{ secrets.GH_TOKEN }}
          ref: dev
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # The Go version to download (if necessary) and use.
      - name: ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
      - run: go version
      - name: Install brotli
        run: | 
          mkdir -p /home/runner/go/src/github.com/Vungle/slydell
          cp -R . /home/runner/go/src/github.com/Vungle/slydell
          git clone --depth 1 --branch v1.1.0 https://github.com/google/brotli.git
          cd brotli
          mkdir out && cd out
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./installed ..
          cmake --build . --config Release --target install
          mkdir /usr/local/include -p
          mkdir /usr/local/lib -p
          sudo cp -r $GITHUB_WORKSPACE/brotli/out/installed/lib/libbrotli* /usr/local/lib/. && \
          sudo cp -r $GITHUB_WORKSPACE/brotli/out/installed/include/brotli /usr/local/include/.
          rm -rf brotli
      - name: Setup build env
        run: |
          git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      - name: Go build
        working-directory: /home/runner/go/src/github.com/Vungle/slydell
        env: 
          GO111MODULE: on
          GOPRIVATE: github.com/Vungle/*
        run: |
          pwd
          CGO_ENABLED=1 GOOS=linux go build -o /home/runner/go/bin/slydell/admin api/admin/cmd/admin-server/main.go
        