name: Build and Publish Images
run-name: ${{inputs.application}} - ${{inputs.image_tag}} - ${{inputs.git_ref}}

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Tag for both amd64 and multi-arch. For example, v1.251.0, PR-xxx.
        type: string
        required: true
      git_ref:
        description: The commit/branch/tag we build for. Keep empty to use default branch.
        type: string
      service:
        description: The service we build for.
        type: string
        required: true
  workflow_call:
    inputs:
      image_tag:
        description: Tag for both amd64 and multi-arch. For example, v1.251.0, PR-xxx.
        type: string
        required: true
      git_ref:
        description: The commit/branch/tag we build for. Keep empty to use default branch.
        type: string
        required: true
      service:
        description: The service we build for.
        type: string
        required: true
permissions:
  id-token: write
  contents: write
  # https://stackoverflow.com/questions/72248956/github-action-with-docker-makes-error-exporting-to-image-403-forbidden-error
  packages: write
  pull-requests: read
env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  build-and-publish:
    name: Build and Publish Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v3  # https://github.com/actions/checkout
        with:
          ref: ${{inputs.git_ref}}
      - run: |
          echo "Building and Publishing Images for ${{inputs.service}}:${{inputs.image_tag}} from ${{inputs.git_ref}}"
