name: Check changes

on:
  workflow_call:
jobs:
  check-change:
    runs-on: ubuntu-latest
    outputs:
      dir1: ${{ steps.check.outputs.dir1 }}
      dir2: ${{ steps.check.outputs.dir1 }}
      dir3: ${{ steps.check.outputs.dir2 }}
      dir4: ${{ steps.check.outputs.dir3 }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: check
        with:
          list-files: 'json'
          filters: |
            dir1:
              - 'dir1/**'
            dir2:
              - 'dir2/**'
            dir3:
              - 'dir3/**'
            dir4:
              - 'dir4/**'
      - run: |
         echo ${{ steps.check.outputs.dir1 }} 
         echo ${{ steps.check.outputs.dir2 }} 
         echo ${{ steps.check.outputs.dir3 }} 
         echo ${{ steps.check.outputs.dir4 }}
