name: Check changes

on:
  workflow_call:
    outputs:
      changes: 
        description: "List of changes"
        value: ${{ jobs.check-change.outputs.changes }}
      contains_changes:
        description: "Check if changes are present"
        value: ${{ jobs.check-change.outputs.changes != '[]' }}
      changes_json:
          description: "Changes in json format for matrix strategy"
          value: ${{ jobs.check-change.outputs.changes_json}}
jobs:
  check-change:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.check.outputs.changes }}
      changes_json: ${{ steps.create-json.outputs.changes_json }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: check
        with:
          list-files: 'csv'
          filters: |
            dir1:
              - 'api/dir1/**'
            dir2:
              - 'api/dir2/**'
            dir3:
              - 'api/dir3/**'
            dir4:
              - 'api/dir4/**'
      - run: |
          echo ${{ steps.check.outputs.dir1 }} 
          echo ${{ steps.check.outputs.dir2 }} 
          echo ${{ steps.check.outputs.dir3 }} 
          echo ${{ steps.check.outputs.dir4 }}
      - name: create json
        id: create-json
        run: | 
          echo ${{ steps.check.outputs.changes }} >> /tmp/changes.csv
          jq -R 'split(",")' /tmp/changes.csv >> /tmp/changes.json
          echo {\"api\":$(jq . /tmp/changes.json)} > /tmp/changes.json
          echo "changes_json=$(cat /tmp/changes.json)" >> $GITHUB_OUTPUT 
