name: PR Creation
on:
  push:
    branches:
      - "action-test"
env:
  ticket_transition: true
  service: jaeger
  version: v1.257.0
  ticket: DEPLOY-1234
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Transistion ticket if true
        if: ${{ env.ticket_transition == 'true'}}
        run: echo "Change ticket status"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: | 
          gh pr create -B main -H action-test --title '${{ env.service }} release ${{ env.version}}' --body 'Deploy ticket: ${{ env.ticket }} \nService: ${{ env.service }} \nVersion: ${{ env.version}}'


