name: PR Creation
on:
  push:
    branches:
      - "action-test"
env:
  ticket_transition: true
  service: jaeger
  version: v1.257.0
  ticket: DEPLOY-1234
jobs:
  zero:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v3
        with:
          ref: main
      - name: merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git status
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout pr-check
          git merge -m 'Sync from master' main
          git push
  one:
    runs-on: ubuntu-latest
    needs:
    - zero
    steps:
      - name: Transistion ticket if true
        if: ${{ env.ticket_transition == 'true'}}
        run: echo "Change ticket status"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: | 
          version=$(echo ${{ env.version}} | sed 's/\./-/g')
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b deployment-${{ env.service }}-$version
          touch test.txt
          echo "foo" >> test.txt
          git add test.txt
          git commit -m 'Release files'
          git pull
          git push origin deployment-${{ env.service }}-$version
          cat << EOF > /tmp/body.txt
          Deploy ticket: ${{ env.ticket }}
          Service: ${{ env.service }}
          Version: ${{ env.version}}
          EOF
          gh pr create -B main -H deployment-${{ env.service }}-$version --title '${{ env.service }} release ${{ env.version}}' -F /tmp/body.txt