name: 'Create release'
# Controls when the action will run.
on:
  repository_dispatch:
    # this is the event_type passed in from the webhook, needs to match exactly what was defined in the webhook custom data payload
    types: ["trigger-deployment"]
  workflow_dispatch:
jobs:
  print-event-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print JIRA ticket number and environment
        run: |
          echo Ticket ${{ github.event.client_payload.issue }}
          echo Ticket ID ${{ github.event.client_payload.issue_id }}
          echo Version ${{ github.event.client_payload.to_version }}
          echo Service ${{ github.event.client_payload.service }}
  start-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App
        uses: actions/checkout@v3
        with:
          path: /tmp/app
      - name: Checkout PE
        uses: actions/checkout@v3
        with:
          ref: deploy
          persist-credentials: true
          repository: Vungle/PE
          token: ${{secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: List files
        run: |
          ls -la pe/apps
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.29.2
      - name: Update chart versions
        run: |
          yq -i e '.spec.template.spec.source.targetRevision = "${{ github.event.client_payload.to_version }}"' ./$(yq '.${{github.event.client_payload.service}}.appfile_prod' /tmp/app/deployment-mapping.yml)

      - name: Commit version update changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./apps/api/*
          git commit -m "Update chart version to ${{ github.event.client_payload.to_version }}" --allow-empty
          git push -f origin deploy
  update-jira:
    runs-on: ubuntu-latest
    name: Create DEPLOY ticket
    needs:
    - start-deployment
    steps:
    - name: Login
      id: login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ github.event.client_payload.issue }}
        transition: "DEPLOYMENT IN PROGRESS"
