name: Deploy QA
on:
  push:
    branches:
      - "dev"
    tags:
      - "qa"
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  init:
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ steps.short-sha.outputs.sha_short }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Get short SHA
        id: short-sha
        shell: bash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  check-changes:
    uses: ./.github/workflows/check-changes.yml
  build-images:
    if: ${{needs.check-changes.outputs.contains_changes == 'true'}}
    needs: 
      - init
      - check-changes
    strategy:
      matrix: ${{fromJson(needs.check-changes.outputs.changes_json)}}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ matrix.api }}
  tag-commit:
    if: ${{ github.event.ref_type == 'branch'}}
    runs-on: ubuntu-latest
    steps:
      - name: Tag commit
        run: |
          git tag --force qa
          git push --force --tags
