name: Deploy feature environment
on:
  push:
    branches: 
    - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  check-changes:
    uses: ./.github/workflows/check-changes.yml
  build-images:
    needs: 
      - check-changes
    strategy:
      matrix:
        api: ${{needs.check-changes.outputs.changes}}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ matrix.api }}
