name: Deploy QA
on:
  push:
    branches:
      - "dev"
    tags:
      - "qa"
  workflow_dispatch:
    inputs:
      extra_tags:
        description: The commit/branch/tag we build for. Keep empty to use default branch.
        type: string
        
      
permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  debug:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get short SHA
        run: 
          skopeo copy --help
      - name: Push extra tags
        if: inputs.extra_tags != ''
        run: |
          for tag in ${{ inputs.extra_tags }}; do
            #skopeo copy --multi-arch all ${{ steps.login-ecr.outputs.registry }}/slydell-${{ inputs.service }}:${{inputs.image_tag}} ${{ steps.login-ecr.outputs.registry }}/slydell-${{ inputs.service }}:$tag
          done
