name: Deploy feature environment
on:
  push:
    branches: 
      - dev
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  check-changes:
    uses: ./.github/workflows/check-changes.yml
  build-images:
    needs: 
      - check-changes
    strategy:
      matrix:
        api:
          - admin
          - alert
          - auth
          - authenticator
          - cron
          - manage
          - mediation
          - metadata
          - processor
          - reporting
          - salesforce
          - scheduler
          - verifyvault
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ matrix.api }}
    
    