name: Deploy QA
on:
  push:
    branches:
      - "dev"
    tags:
      - "qa"
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get short SHA
        run: 
          skopeo copy --help
