name: Deploy Stage
on:
  create: 
  push:
    tags:
      - "stage"
permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  check:
    runs-on: ubuntu-latest
    if: ${{ (github.event.ref_type == 'branch' && contains(github.event.ref, 'release')) || (github.event_name == 'push' && github.ref_name == 'stage')}}
    steps:
    - run: echo "Check OK, release branch created."
  build-images:
    needs: 
        - check
    strategy:
      matrix:
        api:
          - admin
          - alert
          - auth
          - authenticator
          - cron
          - manage
          - mediation
          - metadata
          - processor
          - reporting
          - salesforce
          - scheduler
          - verifyvault
    uses: ./.github/workflows/build-image.yml
    with:
      git_ref: ${{github.ref}}
      service: ${{ matrix.api }}
      environment: stage
    secrets: inherit
  tag-commit:
    if: ${{ github.event.ref_type == 'branch' && contains(github.event.ref, 'release')}}
    needs: 
        - build-images
    runs-on: ubuntu-latest
    steps:
      - name: Tag commit
        run: |
          git tag --force stage
          git push --force --tags
