name: Test wrokflow
on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: |
        echo "foobar" 
    - name: Login
      id: login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: DEPLOY-3924
        transition: Deployment Started