name: Test wrokflow
on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: |
        echo "foobar" 

  