name: Test wrokflow
on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: |
        echo "foobar" 
    - name: Login
      id: login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Transition issue
      id: transition
      uses: atlassian/gajira-transition@v3
      continue-on-error: true
      with:
        issue: DEPLOY-3924
        transition: Deployment Started
    - name: Check state and comment
      if: job.steps.bad.status == failure()
      uses: atlassian/gajira-comment@v3
      with:
        issue: DEPLOY-3924
        comment: Deployment executed succesfully. *No need to manually change the ticket state to Deployment in Progress. Automation does it for you.*
      