name: Fail
on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fail or Success
      run: |
        exit $(( RANDOM % 2 ))
