name: Jobs and steps
on:
  workflow_dispatch:
jobs:
  create-and-list:
    runs-on: ubuntu-latest
    steps:
    - name: Create file
      run: |
        touch /tmp/file.txt
    - name: List file
      run: |
        ls -la /tmp/file.txt

  list:
    runs-on: ubuntu-latest
    steps:
    - name: List file
      run: |
        ls -la /tmp/file.txt


