name: Start deployment
on:
  pull_request:
    branches:
    - 'master'
jobs:
  test-helm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.18.20
          - v1.22.5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get version
        uses: actions/tag-version-action@v1
        id: version
        with:
          command: 'minor'
          args: '-fis'
      - name: Print version
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.28.1
      - name: Update Chart.yaml
        run: |
          yq -i e '.version = "${{ steps.version.outputs.version }}",.appVersion = "${{ steps.version.outputs.version }}"' ./example/helm/Chart.yaml
      - name: Update image.tag
        run: |
          yq -i e '.image.tag = "${{ steps.version.outputs.version }}"' ./example/helm/values.yaml
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.3.0
        with:
          version: v0.16.0
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Add bitnami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Add elastic repo
        run: helm repo add elastic https://helm.elastic.co
      - name: Run chart-testing (lint-andd-install)
        run: ct lint-and-install --chart-dirs=example/helm --charts example/helm --target-branch=master --debug=true --helm-extra-args="--timeout 300s"
