name: Merge to main
on:
  pull_request:
    branches: 
      - main
    types: [closed]
    
jobs:
  check-if-release:
    if: github.event.pull_request.merged && contains(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Next version
        uses: teroahonen-vungle/tag-version-action@v1.0.0
        id: version3
        with:
          command: 'minor'
          args: '-fis -m main'
      - name: debug
        run: echo ${{ steps.version3.outputs.version }}
      - name: create release
        env:
         GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.version3.outputs.version }}-foo -t ${{ steps.version3.outputs.version }}-foo -n ${{ steps.version3.outputs.version }}-foo
