name: 'Create release'
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  CHART_DIR: example/helm/example
  CHART: example
  REPO: charts/example
  SERVICE: example
  DEPLOY_DATA: deploy-data.yml

jobs:
  get-info:
    name: Get release info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
      commit-id: ${{ steps.commit-id.outputs.sha_short }}
      current-version: ${{ steps.current-version.outputs.current_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get release
        id: release
        run: |
          echo "version=$(echo ${{ github.ref }} | cut -d/ -f3)" >> $GITHUB_OUTPUT
      - name: Get commit SHA
        id: commit-id
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: deploy
          persist-credentials: true
          repository: Vungle/PE
          token: ${{secrets.GH_TOKEN }}
          fetch-depth: 0
          path: pe
      - name: Get current version
        id: current-version
        run: | 
           echo "current_version=$(yq '.spec.template.spec.source.targetRevision' pe/apps/example/example-prod-appset.yml)" >> $GITHUB_OUTPUT