name: Retry
on:
  workflow_run:
    workflows: ["fail"]
    branches:
      - main
    types:
      - completed

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  retry:
    runs-on: ubuntu-latest
    steps:
    - name: Retry
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh run rerun ${{ github.event.workflow_run.id }}

