name: Service containers
on:
  workflow_dispatch:
jobs:
  service-container:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest
    container: alpline:latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Test redis
        run: |
          ping -c 5 -W 2 redis

