name: Trigger deployment for QA environment

on:
  pull_request:
    types: 
      - labeled
permissions:
  id-token: write
  contents: write
  # https://stackoverflow.com/questions/72248956/github-action-with-docker-makes-error-exporting-to-image-403-forbidden-error
  packages: write
  pull-requests: read
env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  trigger-build-and-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'qa'}}
    steps:
     - run: |
        echo "Foobar"
  tag-commit:
    runs-on: ubuntu-latest
    needs: 
    - trigger-build-and-publish
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Tag commit
      run: |
        git tag --force qa
        git push --force --tags
